### ISSUE TITLE
Include an outline?

### ISSUE THREAD

**Issue by sckott** [ropensci/user2016-tutorial#1]
Looks like other tutorials include an outline, e.g, http://user2016.org/tutorials/02.html

a start:
1. Overview of data on the web (APIs, ftp, files, scraping, etc.)
2. Working with APIs
3. Scraping web pages
4. ?
5. ?

@garrettgman @karthik

**Comment by karthik** [comment]
I don't think we need to include one for now. But as we get closer to the event, yes.
