### ISSUE TITLE
keynote template

### ISSUE THREAD

**Issue by sckott** [ropensci/user2016-tutorial#2]
@garrettgman never used a keynote template before. When I edit the first title slide, seems that ruins the formatting on the rest of the slides. Any tips?

**Comment by karthik** [comment]
Works fine for me. What version of keynote?

**Comment by garrettgman** [comment]
Short answer: Don't copy and paste the first slide to make new slides.

Longer answer: Each keynote slide inherits its layout from a template "Master slide." If you edit a master slide, every slide that uses it will inherit the changes. The text on the title slide is set on the master slide. If you edit the master slide to change it, all other slides that use the same master will inherit the changes (e.g. any slide that you copied from the title slide).

Sorry for the mix up. This is really only a problem for the title slide. The text on the other slides is set on a  slide by slide level. They only inherit their backgrounds and maybe the general presence of a text box. e.g. they are safer to copy and reuse.

**Comment by sckott** [comment]
thanks @garrettgman !
