### ISSUE TITLE
API to use for exercises

### ISSUE THREAD

**Issue by sckott** [ropensci/user2016-tutorial#3]
http://www.omdbapi.com/ is nice, but it doesn't allow anything other than `GET` requests, correct?

at least for the section i'm doing i'm thinking of using https://httpbin.org/ instead so everyone can easily play with all http verbs, 

that okay? 

can default to omdbapi for all GET requests for consistency with following sections

**Comment by karthik** [comment]
For the first part httpbin would seem fine. We didn't agree to stick with omdb for the main exercise. I'm going to use the random names API to help people build their own.

**Comment by sckott** [comment]
okay, so random names is fine. where is that?

**Comment by karthik** [comment]
It's the API behind my randnames package. It shouldn't be used in the first part because it is the exercise for part II and what people will write a basic package around.

**Comment by karthik** [comment]
In case it wasn't clear, I was saying that httpbin is great for the first intro part.

**Comment by sckott** [comment]
sounds good
