### ISSUE TITLE
The tutorial webpage does not exist

### ISSUE THREAD

**Issue by daattali** [ropensci/user2016-tutorial#4]
In the README it says that all material will be available at `http://ropensci.github.io/user2016-tutorial/` including instructions for what to do prior to the tutorial.  This makes it sound like the webpage should be available already so that people will have time to complete the setup.  That URL does not exist.

**Comment by karthik** [comment]
Thanks Dean. We switched to using keynote presentations and will update that URL after the tutorial with links to the talks and PDFs.
