### ISSUE TITLE
Slide rationalization

### ISSUE THREAD

**Issue by jennybc** [ropensci/user2016-tutorial#5]
Thanks @garrettgman for providing the 3 Keynote files for this! Thanks to you all for making the materials available, it was hugely helpful to me this week.

I was perusing the slides here, since this where my STAT 545 students are coming to grab the PDF. I have 2 suggestions

  * Consider deleting 03-Web-Scraping.pdf, since I think it is superseded by the final 1/3 of slides.pdf?
  * Consider splitting slides.pdf into the 3 decks? For easier navigation and perusal.

**Comment by jennybc** [comment]
I am in a good position to do this right now by the way, so if you want it done, say the word and I will make the PR.

**Comment by cderv** [comment]
As *slide.pdf* no more exists since the commits related to this issue, the github repo `README.md` should be updated because the link at the end do not work anymore, in this line :

> Website for materials: All slides from the workshop are available as a PDF in this repo.
